baseURL: /
languageCode: en-gb
title: Kured

module:
  proxy: direct
  imports:
    - path: github.com/google/docsy
    - path: github.com/google/docsy/dependencies

outputs:
  home: [HTML]
  page: [HTML]

params:
  description: Kured (KUbernetes REboot Daemon) is a Kubernetes daemonset that performs safe automatic node reboots when the need to do so is indicated by the package management system of the underlying OS.
  copyright: The Kured authors
  github_repo: https://github.com/kuberoot/website
  github_branch: main
  github_project_repo: https://github.com/kubereboot/kured
  ui:
    # Enable to show the side bar menu in its compact state.
    sidebar_menu_compact: true
    sidebar_menu_foldable: true
    sidebar_menu_truncate: 1000
    # Set to true to disable breadcrumb navigation.
    breadcrumb_disable: false
    # Set to true to hide the sidebar search box (the top nav search box will still be displayed if search is enabled)
    sidebar_search_disable: true
    # Set to false if you don't want to display a logo (/assets/icons/logo.svg) in the top nav bar
    # -> change once we have SVG
    navbar_logo: false
    # Set to true to disable the About link in the site footer
    footer_about_disable: false
    readingtime:
      enable: false
  links:
    user:
      - name: Slack
        url: 'https://cloud-native.slack.com/archives/kured'
        icon: fab fa-slack
        desc: Chat with other project developers
      - name: Twitter
        url: 'https://twitter.com/kubereboot'
        icon: fab fa-twitter
        desc: Follow us on Twitter to get the latest news!
    developer:
      - name: GitHub
        url: 'https://github.com/kubereboot'
        icon: fab fa-github
        desc: Development takes place here!
      - name: YouTube
        url: 'https://www.youtube.com/playlist?list=PL7wDX91NpJl_rKYrAtd8zr2XszpexS1eE'
        icon: fab fa-youtube
        desc: View the Kured Dev meeting recordings
